### PR TITLE
Add Github Actions CI

### LINKED ISSUE #19: CI builds
We need an automated CI process.

### PR DESCRIPTION
**Pull request by caspiano**
- Simple spec matrix that covers a range of versions.
- Linting via [ameba](https://github.com/crystal-ameba/ameba)
- Ensures standard formatting via `crystal tool format --check`

I also ran `crystal tool format`

Closes #19

### CODE REVIEW

**Comment by caspiano** [comment]
Looks like Github Actions needs to be enabled on this repository

**Comment by icy-arctic-fox** [comment]
> Looks like Github Actions needs to be enabled on this repository

I think the `pull_request` event needs to be added, then we can approve the workflow to run.

**Comment by caspiano** [comment]
Ahh! Will add.

Example run [here](https://github.com/caspiano/processing.cr/actions/runs/1340462073).

**Comment by icy-arctic-fox** [comment]
Seems like it won't run on this PR because it has already been opened and nothing is triggering it. It should run on merge though.

It looks good to me, thanks for the quick implementation!
We're trying to get this repo set up for Hacktoberfest (#17), do you want to get credit for that?

**Review by icy-arctic-fox — APPROVED** [review]

**Comment by caspiano** [comment]
For sure!

**Pull request merged**
